[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_ldf_mode = deep+
build_flags =
    -std=gnu++17
lib_deps =
    https://github.com/simplefoc/Arduino-FOC.git
    https://github.com/bblanchon/ArduinoJson.git

